version: '3.8'

services:
  web:
    build: .
    command: gunicorn https_project.wsgi:application --bind 0.0.0.0:8000 # django entry point
    volumes:
      - .:/usr/src/app # mount a volume so that we don't have to rebuild everytime we make a change
    expose:
      - "8000" # expose the port to nginx container

  nginx:
    build: ./nginx
    ports:
      - "8888:433"
    depends_on:
      - web

